Add function to get MU RX status flags
nxp-mcuxpresso/mcux-sdk pull request #214
Opened 2024-10-10 16:58 UTC by alxlastur

The fsl_mu.h driver need a function
(static inline uint32_t MU_GetRxStatusFlags(MU_Type *base)) that get the MU RX status flags, because ipm_imx.c driver from zephyr/drivers/ipm get the RX status flags directly from MU register instead of using a function. As ipm_imx.c driver is used by multiple imx platforms that have different MU regiter map layout, each platform need to implement a
'static inline uint32_t MU_GetRxStatusFlags(MU_Type *base)' function that will be used by the ipm_imx.c in imx_mu_isr(). As imx_mu_isr() parse the RX status flags in reverse numerical order, the function need to return the RX status flags the same way.

**Prerequisites**

- [ ] I have checked latest main branch and the issue still exists.
- [ ] I did not see it is stated as known-issue in release notes.
- [ ] No similar GitHub issue is related to this change.
- [ ] My code follows the commit guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.

**Describe the pull request**

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

**Tests**

- Test configuration (please complete the following information):
  - Hardware setting:
  - Toolchain:
  - Test Tool preparation:
  - Any other dependencies:
- Test executed
  Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
  - [ ] Build Test
  - [ ] Run Test

2024-10-11 01:45 UTC, zejiang0jason requested changes

2024-10-11 01:45 UTC, zejiang0jason commented on drivers/mu/fsl_mu.h
> +    flags = ((MU_GetStatusFlags(base) >> kMU_Rx0FullFlag) | 0x0000000F);
`>> kMU_Rx0FullFlag` is wrong, because `kMU_Rx0FullFlag` is 0x00800000, then this function always returns 0.

2024-10-11 01:45 UTC, zejiang0jason commented on drivers/mu/fsl_mu.h
> +    flags = ((MU_GetStatusFlags(base) >> kMU_Rx0FullFlag) | 0x0000000F);
please use `0x0000000FU`, to specify it is a unsigned value.

2024-10-11 01:45 UTC, zejiang0jason commented on drivers/mu1/fsl_mu.h
> +    flags = ((MU_GetStatusFlags(base) >> kMU_Rx0FullFlag) | 0x0000000F);
please reconsider the `>> kMU_Rx0FullFlag`, thanks.

2024-10-11 13:14 UTC, alxlastur commented on drivers/mu/fsl_mu.h
> +    flags = ((MU_GetStatusFlags(base) >> kMU_Rx0FullFlag) | 0x0000000F);
yes, that was my mistake. thank you. I need to make some tests and I will make another push

2024-10-11 13:45 UTC, alxlastur commented on drivers/mu/fsl_mu.h
> +    flags = ((MU_GetStatusFlags(base) >> kMU_Rx0FullFlag) | 0x0000000F);
now I made the changes. let me know you feedback

2024-10-11 13:45 UTC, alxlastur commented on drivers/mu/fsl_mu.h
> +    flags = ((MU_GetStatusFlags(base) >> kMU_Rx0FullFlag) | 0x0000000F);
done

2024-10-11 13:45 UTC, alxlastur commented on drivers/mu1/fsl_mu.h
> +    flags = ((MU_GetStatusFlags(base) >> kMU_Rx0FullFlag) | 0x0000000F);
done

2024-10-18 12:37 UTC, MichalPrincNXP commented
... will be solved internally ...

2024-10-18 12:37 UTC, closed without merging